name: merge_music
description: "MergeMusic"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.8.0
  intl: ^0.19.0
  provider: ^6.1.2
  vkid_flutter_sdk: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
  fonts:
    - family: VK Sans Display
      fonts:
      - asset: assets/fonts/VKSansDisplay-Regular.ttf
        weight: 400
      - asset: assets/fonts/VKSansDisplay-Medium.ttf
        weight: 500
      - asset: assets/fonts/VKSansDisplay-DemiBold.ttf
        weight: 600
      - asset: assets/fonts/VKSansDisplay-Bold.ttf
        weight: 700
      